# Use an official Node.js runtime as a parent image
FROM node:22-alpine
# Set the working directory in the container
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install the dependencies
RUN npm install
# Copy the rest of the application code to the working directory in the container
# first . means the source folder on host
# second . means the destination folder in the container 
COPY . .
# Expose the port the app runs on
EXPOSE 4200
# Start the application
CMD ["npm", "run", "start"]